# Writes generated/BuildInfo.h -- version, git commit and build date --
# on every build (a custom target, not configure time, so Hilfe › Über
# never shows a commit the working tree left behind weeks ago). The
# file is only rewritten when its content changes, so nothing
# recompiles needlessly. Arguments: -DOUTPUT -DSOURCE_DIR -DVERSION.
execute_process(COMMAND git -C "${SOURCE_DIR}" rev-parse --short=10 HEAD
                OUTPUT_VARIABLE GIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
execute_process(COMMAND git -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
                OUTPUT_VARIABLE GIT_DIRTY ERROR_QUIET)
if(NOT GIT_HASH)
    set(GIT_HASH "unbekannt")
endif()
if(GIT_DIRTY)
    # Uncommitted changes in the tree this was built from.
    set(GIT_HASH "${GIT_HASH}+")
endif()
string(TIMESTAMP BUILD_DATE "%Y-%m-%d" UTC)
set(CONTENT "#pragma once
// Generated by cmake/BuildInfo.cmake on every build -- do not edit.
#define CONTESTPROGRAMM_VERSION \"${VERSION}\"
#define CONTESTPROGRAMM_GIT_HASH \"${GIT_HASH}\"
#define CONTESTPROGRAMM_BUILD_DATE \"${BUILD_DATE}\"
")
set(OLD "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" OLD)
endif()
if(NOT OLD STREQUAL CONTENT)
    file(WRITE "${OUTPUT}" "${CONTENT}")
endif()
